# Site settings
title: "Pedram Khorsandi"
description: "Ph.D. student at Mila – Quebec Institute of Artificial Intelligence specializing in Optimization in Federated Learning and Performative Prediction."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Pedram Khorsandi"
resume_title:                   "About"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "pedram.khorsandi [at] mila.quebec"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "000"
resume_contact_address:         "000"

resume_header_contact_info:     ""
display_header_contact_info:    "true"

resume_header_intro: "<p>I am a PhD student at Mila and the University of Montréal, supervised by Simon Lacoste-Julien. My research focuses on optimization in performative setups.</p><p>Before joining Mila, I completed my BSc in Computer Engineering at Sharif University of Technology.</p><p>My work explores convergence properties and optimization techniques in performative setups. I have also worked on few-shot semantic segmentation and socially-aware trajectory prediction.</p><p>I maintain an active interest in theoretical optimization and algorithmic design.</p><p style="font-family: monospace;">pedram.khorsandi [at] mila.quebec</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
# resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/pedramkho"
  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  # resume_facebook_url:          ""
  resume_linkedin_url:          "https://www.linkedin.com/in/pedram-khorsandi-257780150/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://pedramkho.github.io"
  # resume_medium_url:            "https://medium.com/@pedramkho"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
